name: Email Identification Action

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 23f2004369@ds.study.iitm.ac.in
        run: echo "Hello, world! The action has been triggered."
